#! /bin/sh

sxhkd &
$HOME/.config/polybar/launch.sh &
$HOME/.screenlayout/default.sh &
$HOME/.scripts/autostart.sh &
feh --bg-scale /home/jordan/Pictures/backgrounds/wallhaven-704123.jpg
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

bspc monitor HDMI2 -d  2 

bspc monitor HDMI1 -d 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap           10 
bspc config bottom_padding       0
bspc config top_padding          0

# Tiling Config
bspc config split_ratio          0.49
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config initial_polarity     first_child
bspc config auto_alternate       true
bspc config auto_cancel          true
bspc config honor_size_hints     true
#bspc config automatic_scheme     alternate

bspc rule -a Screenkey manage=off
bspc rule -a firefox desktop='^4'
bspc rule -a discord desktop='^5'
bspc rule -a spotify desktop='^5'
bspc rule -a tsun-awt-X11-XDialogPeer state=floating
bspc rule -a Gnome-calculator state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a edu-sbcc-cs105-Program state=floating
bspc rule -a parsecd desktop='^3'

# Themeing
bspc config normal_border_color "#292D3E"
bspc config focused_border_color "#82AAFF"

